### ISSUE TITLE
[BUG] Cannot load mod 

### ISSUE THREAD

**Issue by Tazdon11** [ColDogStudios/BMC-Mod#2]
**Describe the bug**
When switching the files, when I try to re open the game afterwards, the game shows the loading screen and then closes immediately after 

**To Reproduce**
Uninstall game 
Reinstall game
Backup save 
Uninstall
Reinstall and switch files 
Open game
Crash will occur

**Expected behavior**
I expected the game to open normally and for me to be able to use the mod

**Screenshots**
Hard to screenshot a game closing, but if you are ever free I am happy to screen record me doing it 

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by ColDogStudios** [comment]
# **[BUG] Cannot load mod:**

## Conclusion:

Several tests were ran with the same, downloadable data.jet file and Bloons Monkey City never crashed on a Windows 11 machine. A problem with the user's machine is the cause of 

## Suggested Fixes:

 1. Ensure you are using the _**Steam**_ version of BMC.
 2. Ensure there are not too many programs/services running to eat up system resources.
 3. Check/Scan for viruses.
 4. Reinstall Steam.

If the problem still occurs after the above suggested fixes, head over to the 'Discussions' tab.
